language: golang

git:
    depth: false
services: 
    - docker

go: 
    - "1.13.x"

dist: xenial
sudo: required

before_install:
    - sudo apt-get update
    - sudo apt-get -y install openjdk-8-jdk
    - sudo docker swarm init

before_script:
    - chmod 0755 ./support.sh ./springcloud.sh

script: 
    - ./support.sh
    - ./springcloud.sh 

after_success: 
    - sudo docker tag closetool/configserver registry.cn-hangzhou.aliyuncs.com/closetool/configserver
    - sudo docker login --username=马桶拔子k -p $aliyun_docker_password registry.cn-hangzhou.aliyuncs.com
    - sudo docker push registry.cn-hangzhou.aliyuncs.com/closetool/configserver