language: go

git:
    depth: false
services: 
    - docker

go: 
    - "1.13.x"

dist: xenial
sudo: required

before_install:
    - sudo apt-get update
    - sudo apt-get -y install openjdk-8-jdk
    - docker swarm init

before_script:
    - docker network create -d overlay my_network
    - chmod 0755 ./support.sh ./springcloud.sh

script: 
    - sudo ./support.sh
    - sudo ./springcloud.sh 

after_success: 
    - docker tag closetool/configserver registry.cn-hangzhou.aliyuncs.com/closetool/configserver
    - docker login --username=马桶拔子k -p $aliyun_docker_password registry.cn-hangzhou.aliyuncs.com
    - docker push registry.cn-hangzhou.aliyuncs.com/closetool/configserver