language: golang

sudo: required

services: 
    - docker

go: 
    - "1.13.x"

before_install:
    - docker swarm init

script: 
    - ./support.sh
    - ./springcloud.sh 
    - go test ./...

after_success: 
    - docker tag closetool/configserver registry.cn-hangzhou.aliyuncs.com/closetool/configserver
    - docker login --username=马桶拔子k -p $aliyun_docker_password registry.cn-hangzhou.aliyuncs.com
    - docker push registry.cn-hangzhou.aliyuncs.com/closetool/configserver