version: "3.3"

services:
    viz:
        image: dockersamples/visualizer
        ports: 
            - "8080:8080/tcp"
        volumes: 
            - "/var/run/docker.sock:/var/run/docker.sock"
        #deploy:
        #    placement:
        #        constranints:
        #            - "node.role==manager"

    mysql:
        build: support/mysql/
        ports:
            - "3306:3306"
        networks:
            - blog
        deploy:
            replicas: 1
    
    rabbitmq: 
        build: support/rabbitmq/
        networks:
            - blog
        ports:
            - "1883:1883" 
            - "5672:5672" 
            - "15672:15672"
        deploy:
            replicas: 1

    springcloud:
        build: support/config-server/
        depends_on:
            - rabbitmq
        networks:
            - blog
        ports:
            - "8888:8888"
        #update_config:
        #    delay: 10s
        #    parallelism: 1
        deploy:
            replicas: 1

    nginx:
        build: support/nginx/
        depends_on: 
            - musicservice
            - userservice
            - categoryservice
        networks:
            - blog
        ports:
            - "9000:9000"
        deploy:
            replicas: 1

    musicservice:
        build: services/musicservice
        depends_on:
            - springcloud
        networks:
            - blog
        ports:
            - "2599:2599"
        deploy:
            replicas: 1
    
    
    userservice:
        build: services/userservice
        depends_on:
            - springcloud
            - mysql
            - rabbitmq
        networks:
            - blog
        ports:
            - "2600:2600"
        deploy:
            replicas: 1

    categoryservice:
        build: services/categoryservice
        depends_on:
            - springcloud
            - mysql
            - rabbitmq
            - userservice
        links: 
            - userservice
        networks:
            - blog
        ports:
            - "2601:2601"
        deploy:
            replicas: 1
    

networks:
    blog: