version: "3"

services:
    viz:
        image: dockersamples/visualizer
        ports: 
            - "8080:8080/tcp"
        volumes: 
            - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            replicas: 1
            placement:
                constraints: [node.role==manager]

    mysql:
        image: closetool/mysql
        ports:
            - "3306:3306"
        networks:
            - overlay
        deploy:
            replicas: 1
    
    rabbitmq: 
        image: closetool/rabbitmq
        networks:
            - overlay
        ports:
            - "1883:1883" 
            - "5672:5672" 
            - "15672:15672"
        deploy:
            replicas: 1

    configserver:
        image: closetool/configserver
        depends_on:
            - rabbitmq
        networks:
            - overlay
        ports:
            - "8888:8888"
        #update_config:
        #    delay: 10s
        #    parallelism: 1
        deploy:
            replicas: 1

    nginx:
        image: closetool/nginx
        depends_on: 
            - musicservice
            - userservice
            - categoryservice
        networks:
            - overlay
        ports:
            - "9000:9000"
        deploy:
            replicas: 1

    musicservice:
        image: closetool/musicservice
        depends_on:
            - springcloud
        networks:
            - overlay
        ports:
            - "2599:2599"
        deploy:
            replicas: 1
    
    
    userservice:
        image: closetool/userservice
        depends_on:
            - springcloud
            - mysql
            - rabbitmq
        networks:
            - overlay
        ports:
            - "2600:2600"
        deploy:
            replicas: 1

    categoryservice:
        image: closetool/categoryservice
        depends_on:
            - springcloud
            - mysql
            - rabbitmq
            - userservice
        links: 
            - userservice
        networks:
            - overlay
        ports:
            - "2601:2601"
        deploy:
            replicas: 1
    
    #lostsservice:
    #    image: closetool/postsservice
    #    depends_on:
    #        - springcloud
    #        - mysql
    #        - rabbitmq
    #        - userservice
    #        - logservice
    #        - categoryservice
    #    networks:
    #        - overlay
    #    ports:
    #        - "2602:2602"
    #    deploy:
    #        replicas: 1

    logservice:
        image: closetool/logservice
        depends_on:
            - springcloud
            - mysql
            - rabbitmq
        networks:
            - overlay
        ports:
            - "2603:2603"
        deploy:
            replicas: 1

networks:
    overlay:
