package blogerrors

const (
	SUCCESS = iota
	ERROR
	DATA_NO_EXIST
	PARAM_ERROR
	LOGIN_DISABLE
	LOGIN_ERROR
	ACCESS_NO_PRIVILEGE
	PARAM_INCORRECT
	INVALID_TOKEN
	REGISTER_ADMIN
	ACCOUNT_EXIST
	ACCOUNT_NOT_EXIST
	PASSWORD_ERROR
	SYNC_POSTS_ERROR
	UPDATE_PASSWORD_ERROR
	FILE_TYPE_ERROR
	IMPORT_FILE_ERROR
	DATABASE_SQL_PARSE_ERROR
)

var Errors = map[int]string{
	SUCCESS: "操作成功",
	ERROR:"操作失败",
	DATA_NO_EXIST: "该数据不存在",
	PARAM_ERROR: "参数错误",
	LOGIN_DISABLE: "账户已被禁用",
	LOGIN_ERROR: "登录失败，用户名或密码错误",
	ACCESS_NO_PRIVILEGE: "不具备访问权限",
	PARAM_INCORRECT: "传入参数有误",
	INVALID_TOKEN: "token解析失败",
	REGISTER_ADMIN: "注册失败",
	ACCOUNT_EXIST: "账号已存在",
	ACCOUNT_NOT_EXIST: "用户不存在",
	PASSWORD_ERROR: "密码错误",
	SYNC_POSTS_ERROR: "同步文章失败",
	UPDATE_PASSWORD_ERROR: "密码修改失败",
	FILE_TYPE_ERROR: "文件类型错误",
	IMPORT_FILE_ERROR: "文件导入失败",
	DATABASE_SQL_PARSE_ERROR: "数据库解析异常",
}

